apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flask-app
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flask-app
    spec:
      containers:
      - image: 387538648925.dkr.ecr.us-east-2.amazonaws.com/flask-app:v2
        name: flask-app
        ports:
        - containerPort: 5000
        resources: {}
status: {}
